### PR TITLE
Front-end capability for location on schedule

### PR DESCRIPTION
**Pull request by marchdan**
Added the necessary elements to allow the class location to display on the frontend

### CODE REVIEW

**Review by Bad-Science — CHANGES_REQUESTED** [review]
Thank you!

Looks like you somehow added commits from the other repository, though. This PR should only include commits 64a683a through 77ee1e5. Not sure how all those commits from yacs-orchestra got in here.

Also, would you mind updating your description to be a bit more specific?

**Comment by marchdan** [comment]
Not sure where to see what changes were requested. I'll make a comment to add specificity

**Comment by marchdan** [comment]
Added a location variable to course-list/section/period.ts
Added a location variable to schedule-view/schedule-event/schedule-event.ts
Added a scheduleEvent.location output in schedule-view-schedule-event/component.html
Added a location event, specifying period.location, in schedule-view.component.ts

**Comment by Bad-Science** [comment]
Thanks @marchdan that's good. Can you remove all of the commits from yacs-orchestra though?

**Comment by marchdan** [comment]
All problems should be fixed and extraneous changes reverted.

**Review by Bad-Science — APPROVED** [review]

**Comment by Bad-Science** [comment]
Thanks @marchdan ! Great work! Merging now!

**Pull request merged**
