### PR TITLE
Initial tests

### PR DESCRIPTION
**Pull request by a-zuckut**
This is the initial test for this repo, basically just to get the code out on the repo.

### CODE REVIEW

**Comment by a-zuckut** [comment]
To Note: Right now I'm just testing simple functionality:

TODO:
- [x] Go over tests to add functionality of ui. (Buttons, links, etc)

**Comment by a-zuckut** [comment]
To note: 
Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'ng:///DynamicTestModule/CourseComponent_Host.ngfactory.js'.
THEN run: ```ng test -sm=false```

**Comment by Bad-Science** [comment]
@a-zuckut Looks great!

I was going to merge it in, and I resolved some merge and dependency conflicts with master. I'm getting a few errors though now, looks like were just caused by some small changes in school-list since this branch was created.

```
ERROR in /Users/richie/Dev/rcos-yacs/yacs-web/src/app/schedule-view/component.spec.ts (11,10): Module '"/Users/richie/Dev/rcos-yacs/yacs-web/src/app/schedule-view/schedule/component"' has no exported member 'Schedule'.

ERROR in /Users/richie/Dev/rcos-yacs/yacs-web/src/app/school-list/component.spec.ts (51,25): Property 'getSchools' does not exist on type 'SchoolListComponent'.

ERROR in /Users/richie/Dev/rcos-yacs/yacs-web/src/app/school-list/component.spec.ts (63,25): Property 'ngOnInit' does not exist on type 'SchoolListComponent'.

ERROR in /Users/richie/Dev/rcos-yacs/yacs-web/src/app/school-list/component.spec.ts (88,15): Property 'getSchools' does not exist on type 'SchoolListComponent'.
```

You can ignore testing schedule-view for now. Once those are resolved we can get this merged :)

**Comment by a-zuckut** [comment]
Need to complete tests for SchoolComponent, DepartmentComponent, and ScheduleViewComponent.

**Review by Bad-Science — APPROVED** [review]
LGTM

**Pull request merged**
