### PR TITLE
Consolidation of disjoint models in central location

### PR DESCRIPTION
**Pull request by marchdan**
Moved modules:
    course-list/course/course.ts
    course-list/section/period.ts
    course-list/section/section.ts
    schedule-view/schedule/schedule.ts
    schedule-view/schedule-event/schedule-event.ts
    school-list/department/department.ts
    school-list/school/school.ts

To yacs-web/src/app/models as _name_.model.ts

And changed imports on all needed files which utilize these files.

Addresses issue #32

### CODE REVIEW

**Comment by Bad-Science** [comment]
@marchdan Thanks!! Could you run the test suite and make sure nothing broke and that the application still builds? I need to get Travis set up... :P

**Comment by marchdan** [comment]
I don’t know if there is a difference between building for development on my machine and the test suite. But it builds fine on my local environment. If there is a separate test suite I should be running, just let me know how.

**Comment by Bad-Science** [comment]
You should be able to run the test suite manually with `bin/yacs-compose-development run --rm web npm test`

**Comment by marchdan** [comment]
All files should now be correct as far as the test suite will show.

**Review by Bad-Science — APPROVED** [review]
@marchdan Looks good! Merging now. Thanks!

**Pull request merged**
